apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: foo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foo-app
  template:
    metadata:
      labels:
        app: foo-app
    spec:
      containers:
        - name: foo-app
          image: hashicorp/http-echo
          args:
              - "-text=Hello from foo-app"

---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  selector:
    app: foo-app
  ports:
  # Default port used by the image
  - port: 5678