# a cluster with 3 control-plane nodes and 3 workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins.\"io.containerd.grpc.v1.cri\".registry.mirrors.\"localhost:${REG_PORT}\"]
      endpoint = [\"http://${REG_IP}:${REG_PORT}\"]
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: ${API_SERVER_ADDRESS}
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: ${API_SERVER_PORT}
nodes:
  #  - role: control-plane
  #  - role: control-plane
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
          authorization-mode: "AlwaysAllow"
    extraPortMappings:
      # extraPortMappings allow the local host to make requests to the Ingress controller over ports 80/443
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 11211
        hostPort: 11211
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 9000 # this port can be used as a NodePort to expose a service
        hostPort: 9001
    extraMounts:
      - hostPath: ${EXTRA_MOUNTS_HOST_PATH}
        containerPath: ${EXTRA_MOUNTS_CONTAINER_PATH}
  - role: worker
    extraPortMappings:
      - containerPort: 9000
        hostPort: 9002
    extraMounts:
      - hostPath: ${EXTRA_MOUNTS_HOST_PATH}
        containerPath: ${EXTRA_MOUNTS_CONTAINER_PATH}
  - role: worker
    extraPortMappings:
      - containerPort: 9000
        hostPort: 9003
    extraMounts:
      - hostPath: ${EXTRA_MOUNTS_HOST_PATH}
        containerPath: ${EXTRA_MOUNTS_CONTAINER_PATH}
#        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
#        protocol: udp # Optional, defaults to tcp
