apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openampvc
  namespace: default
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
#    - ReadWriteMany
  storageClassName: local-storage
