apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailslurper-local-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteMany
  #    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: ${EXTRA_MOUNTS_CONTAINER_PATH}/mailslurper/config.json

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mailslurper-app
spec:
  serviceName: mailslurper-service
  replicas: 1
  selector:
    matchLabels:
      app: mailslurper-app
  template:
    metadata:
      labels:
        app: mailslurper-app
    spec:
      containers:
        - image: marcopas/docker-mailslurper
          name: mailslurper
          volumeMounts:
            - name: mailslurperpvc
              mountPath: /opt/mailslurper/config.json
          ports:
            - name: www-port
              containerPort: 8082
              protocol: TCP
            - name: service-port
              containerPort: 8085
              protocol: TCP
            - name: smtp-port
              containerPort: 2500
              protocol: TCP
  volumeClaimTemplates:
    - metadata:
        name: mailslurperpvc
      spec:
        resources:
          requests:
            storage: 128Mi
        volumeName: mailslurper-local-pv
        accessModes:
          #    - ReadWriteOnce
          - ReadWriteMany
        storageClassName: \"\"
---

